import Head from 'next/head';
import Footer from '@components/Footer';
import Header from '@components/Header';
import ContactUs from '@sections/ContactUs';
import styles from 'styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Webtronics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <ContactUs />
      </main>
      <Footer />
    </>
  );
}
