import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/main.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Webtronics | Frontend developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.cdnfonts.com/css/clash-display" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Front-End Developer</h1>
        <p className="p1">
          Make UIs and websites beautiful, functional,
          and fast. Cover all the topics that expensive bootcamps teach (and more). 
        </p>
      </main>
    </>
  )
}
